# General
min_particles: 500
max_particles: 3000
kld_err: 0.01
update_min_d: 0.1
update_min_a: 0.25
resample_interval: 1
transform_tolerance: 0.5
recovery_alpha_slow: 0.00
recovery_alpha_fast: 0.00
gui_publish_rate: -1.0

# Laser scan
scan: scan
laser_max_range: 3.5
laser_max_beams: 150
laser_z_hit: 0.5
laser_z_short: 0.05
laser_z_max: 0.05
laser_z_rand: 0.5
laser_sigma_hit: 0.2
laser_lambda_short: 0.1
laser_likelihood_max_dist: 2.0
laser_model_type: likelihood_field

# Odometry
odom_model_type: diff
odom_alpha1: 0.2
odom_alpha2: 0.2
odom_alpha3: 0.2
odom_alpha4: 0.2
odom_frame_id: odom
base_frame_id: base_footprint